
package local.charles.module.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault6", targetNamespace = "urn:Manager")
public class ManagerTimeoutException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ManagerTimeoutException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ManagerTimeoutException_Exception(String message, ManagerTimeoutException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ManagerTimeoutException_Exception(String message, ManagerTimeoutException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: local.charles.module.ws.ManagerTimeoutException
     */
    public ManagerTimeoutException getFaultInfo() {
        return faultInfo;
    }

}
