
package local.charles.module.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault7", targetNamespace = "urn:Manager")
public class ManagerValidationException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ManagerValidationException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ManagerValidationException_Exception(String message, ManagerValidationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ManagerValidationException_Exception(String message, ManagerValidationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: local.charles.module.ws.ManagerValidationException
     */
    public ManagerValidationException getFaultInfo() {
        return faultInfo;
    }

}
