
package local.charles.module.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ManagerService", targetNamespace = "urn:Manager", wsdlLocation = "https://DSM.vcp.local:4119/webservice/Manager?WSDL")
public class ManagerService
    extends Service
{

    private final static URL MANAGERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(local.charles.module.ws.ManagerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = local.charles.module.ws.ManagerService.class.getResource(".");
            url = new URL(baseUrl, "https://DSM.vcp.local:4119/webservice/Manager?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://DSM.vcp.local:4119/webservice/Manager?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MANAGERSERVICE_WSDL_LOCATION = url;
    }

    public ManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagerService() {
        super(MANAGERSERVICE_WSDL_LOCATION, new QName("urn:Manager", "ManagerService"));
    }

    /**
     * 
     * @return
     *     returns Manager
     */
    @WebEndpoint(name = "Manager")
    public Manager getManager() {
        return super.getPort(new QName("urn:Manager", "Manager"), Manager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Manager
     */
    @WebEndpoint(name = "Manager")
    public Manager getManager(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Manager", "Manager"), Manager.class, features);
    }

}
