
package local.charles.module.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault4", targetNamespace = "urn:Manager")
public class ManagerSecurityException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ManagerSecurityException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ManagerSecurityException_Exception(String message, ManagerSecurityException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ManagerSecurityException_Exception(String message, ManagerSecurityException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: local.charles.module.ws.ManagerSecurityException
     */
    public ManagerSecurityException getFaultInfo() {
        return faultInfo;
    }

}
